FROM python:3.9

WORKDIR /app

COPY ./backend/requirements.txt ./backend/

RUN pip3 install -r ./backend/requirements.txt

COPY ./backend/src ./backend/src
COPY ./backend/swagger_doc ./backend/swagger_doc

COPY ./easychair_scraper ./easychair_scraper

COPY .env ./

EXPOSE 5000

CMD [ "python3", "-m", "backend.src.server" ]