version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000 # this defines the URL the frontend makes requests to
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.scheduler
