FROM python:3.9

WORKDIR /app

COPY ./backend/requirements.txt ./backend/

RUN pip3 install -r ./backend/requirements.txt

COPY ./backend/src ./backend/src

COPY .env ./

CMD [ "python3", "-m", "backend.src.schedule" ]